import io
from openpyxl import Workbook
from openpyxl.styles import Font, Alignment, PatternFill, Border, Side

def generate_excel_report(report_type: str, data: dict) -> io.BytesIO:
    wb = Workbook()
    ws = wb.active
    ws.title = "Operational Summary"

    # Styles
    title_font = Font(name="Arial", size=14, bold=True, color="082F49")
    header_font = Font(name="Arial", size=11, bold=True, color="FFFFFF")
    bold_font = Font(name="Arial", size=10, bold=True)
    regular_font = Font(name="Arial", size=10)
    
    header_fill = PatternFill(start_color="0EA5E9", end_color="0EA5E9", fill_type="solid")
    
    thin_border_side = Side(border_style="thin", color="D1D5DB")
    thin_border = Border(left=thin_border_side, right=thin_border_side, top=thin_border_side, bottom=thin_border_side)
    
    # 1. Add Title
    ws.merge_cells("A1:B1")
    ws["A1"] = "PVCPilot AI — Operational Report"
    ws["A1"].font = title_font
    ws["A1"].alignment = Alignment(horizontal="center")
    
    ws["A2"] = "Manufacturing Intelligence Platform"
    ws["A2"].font = Font(name="Arial", size=9, italic=True)
    
    ws["A4"] = "Report Type"
    ws["A4"].font = bold_font
    ws["B4"] = report_type.replace("_", " ").title()
    ws["B4"].font = regular_font

    # Table Header
    ws["A6"] = "Metric Name"
    ws["A6"].font = header_font
    ws["A6"].fill = header_fill
    ws["A6"].alignment = Alignment(horizontal="left")
    
    ws["B6"] = "Value"
    ws["B6"].font = header_font
    ws["B6"].fill = header_fill
    ws["B6"].alignment = Alignment(horizontal="left")
    
    # Fill Data
    row = 7
    for key, val in data.items():
        ws.cell(row=row, column=1, value=key.replace("_", " ").title()).font = regular_font
        ws.cell(row=row, column=1).border = thin_border
        
        ws.cell(row=row, column=2, value=str(val)).font = regular_font
        ws.cell(row=row, column=2).border = thin_border
        row += 1
        
    # Auto-adjust column width
    from openpyxl.utils import get_column_letter
    for col in ws.columns:
        max_len = max(len(str(cell.value or '')) for cell in col)
        col_letter = get_column_letter(col[0].column)
        ws.column_dimensions[col_letter].width = max(max_len + 4, 25)
        
    # Append the custom branding footer
    row += 2
    ws.merge_cells(start_row=row, start_column=1, end_row=row, end_column=2)
    ws["A" + str(row)] = "PVCPilot AI — Manufacturing Intelligence Platform"
    ws["A" + str(row)].font = Font(name="Arial", size=10, bold=True, color="0EA5E9")
    ws["A" + str(row)].alignment = Alignment(horizontal="center")
    
    row += 1
    ws.merge_cells(start_row=row, start_column=1, end_row=row, end_column=2)
    ws["A" + str(row)] = "Intelligent Factory Operations Platform"
    ws["A" + str(row)].font = Font(name="Arial", size=8, italic=True)
    ws["A" + str(row)].alignment = Alignment(horizontal="center")
    
    row += 1
    ws.merge_cells(start_row=row, start_column=1, end_row=row, end_column=2)
    ws["A" + str(row)] = "PVCPilot AI — Operational Report"
    ws["A" + str(row)].font = Font(name="Arial", size=8, color="71717A")
    ws["A" + str(row)].alignment = Alignment(horizontal="center")

    row += 1
    ws.merge_cells(start_row=row, start_column=1, end_row=row, end_column=2)
    ws["A" + str(row)] = "This report is generated by PVCPilot AI and is intended for internal use only."
    ws["A" + str(row)].font = Font(name="Arial", size=7, color="71717A")
    ws["A" + str(row)].alignment = Alignment(horizontal="center")

    buffer = io.BytesIO()
    wb.save(buffer)
    buffer.seek(0)
    return buffer
