import io
from datetime import datetime
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER

def generate_pdf_report(report_type: str, data: dict) -> io.BytesIO:
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=letter, rightMargin=36, leftMargin=36, topMargin=36, bottomMargin=36)
    
    styles = getSampleStyleSheet()
    
    # Custom Styles
    title_style = ParagraphStyle(
        'TitleStyle',
        parent=styles['Heading1'],
        fontSize=18,
        textColor=colors.HexColor('#082F49'),
        spaceAfter=12
    )
    
    header_style = ParagraphStyle(
        'HeaderStyle',
        parent=styles['Normal'],
        fontSize=10,
        textColor=colors.HexColor('#6B7280'),
        spaceAfter=24
    )
    
    section_style = ParagraphStyle(
        'SectionStyle',
        parent=styles['Heading2'],
        fontSize=12,
        textColor=colors.HexColor('#0EA5E9'),
        spaceBefore=12,
        spaceAfter=6
    )
    
    body_style = ParagraphStyle(
        'BodyStyle',
        parent=styles['BodyText'],
        fontSize=10,
        textColor=colors.HexColor('#1F2937'),
        spaceAfter=6
    )

    story = []
    
    # 1. Header
    story.append(Paragraph("PVCPilot AI — Manufacturing Intelligence Platform", title_style))
    story.append(Paragraph(f"Generated by PVCPilot AI | Date: {datetime.utcnow().strftime('%d %b %Y, %H:%M:%S UTC')}", header_style))
    story.append(Spacer(1, 10))
    
    # 2. Summary
    story.append(Paragraph(f"Report Type: {report_type.replace('_', ' ').title()}", section_style))
    story.append(Paragraph("This document contains a comprehensive diagnostic summary of factory operations including machine performance, energy consumption, raw materials inventory status, and quality control tests.", body_style))
    story.append(Spacer(1, 10))

    # 3. Data Table
    table_data = [[Paragraph("<b>Metric Name</b>", body_style), Paragraph("<b>Value</b>", body_style)]]
    for key, val in data.items():
        metric_name = key.replace("_", " ").title()
        metric_val = str(val)
        table_data.append([Paragraph(metric_name, body_style), Paragraph(metric_val, body_style)])
        
    t = Table(table_data, colWidths=[200, 200])
    t.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,0), colors.HexColor('#F3F4F6')),
        ('ALIGN', (0,0), (-1,-1), 'LEFT'),
        ('BOTTOMPADDING', (0,0), (-1,0), 6),
        ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor('#E5E7EB')),
        ('TOPPADDING', (0,0), (-1,-1), 6),
        ('BOTTOMPADDING', (0,0), (-1,-1), 6),
    ]))
    story.append(t)
    story.append(Spacer(1, 20))
    
    # 4. Build Footer Elements
    doc_width = doc.pagesize[0] - doc.leftMargin - doc.rightMargin
    footer_elements = build_report_footer(doc_width)
    story.extend(footer_elements)

    doc.build(story)
    buffer.seek(0)
    return buffer

def build_report_footer(doc_width: float) -> list:
    """
    Builds the footer section for all PVCPilot AI PDF reports.
    Includes copyright and platform branding.
    """
    elements = []

    elements.append(Spacer(1, 24))
    
    # Custom line instead of HRFlowable to ensure 100% compatibility
    line_table = Table([[""]], colWidths=[doc_width])
    line_table.setStyle(TableStyle([
        ('LINEABOVE', (0,0), (-1,-1), 0.5, colors.HexColor('#71717A')),
        ('BOTTOMPADDING', (0,0), (-1,-1), 0),
        ('TOPPADDING', (0,0), (-1,-1), 0),
    ]))
    elements.append(line_table)
    elements.append(Spacer(1, 10))

    footer_style = ParagraphStyle(
        'footer',
        fontSize=8,
        textColor=colors.HexColor('#71717A'),
        alignment=TA_CENTER,
        leading=14,
    )

    brand_style = ParagraphStyle(
        'brand',
        fontSize=9,
        textColor=colors.HexColor('#0EA5E9'),
        alignment=TA_CENTER,
        fontName='Helvetica-Bold',
    )

    elements.append(Paragraph("PVCPilot AI — Manufacturing Intelligence Platform", brand_style))
    elements.append(Spacer(1, 4))
    elements.append(Paragraph(
        "Intelligent Factory Operations Platform",
        footer_style,
    ))
    elements.append(Spacer(1, 6))


    elements.append(Spacer(1, 6))

    elements.append(Paragraph(
        "This report is generated by PVCPilot AI and is intended for internal use only. "
        "Data accuracy depends on real-time sensor and ERP integration.",
        footer_style,
    ))

    return elements

